INSERT INTO LOGIN_CREDENTIALS VALUES('JOEL','1234');
INSERT INTO LOGIN_CREDENTIALS VALUES('DEEPAK','1224');
INSERT INTO LOGIN_CREDENTIALS VALUES('kAYATHRI','1334');
INSERT INTO THEATRE_MOVIE_MODEL ("ID","MOVIE_ID","THEATRE","THEATRE_ID" ) VALUES (1,111,'Satyam',222);
INSERT INTO THEATRE_MOVIE_MODEL ("ID","MOVIE_ID","THEATRE","THEATRE_ID" ) VALUES (2,112,'Satyam',222);
INSERT INTO THEATRE_MOVIE_MODEL ("ID","MOVIE_ID","THEATRE","THEATRE_ID" ) VALUES (3,113,'Luxe',223);
INSERT INTO THEATRE_MOVIE_MODEL ("ID","MOVIE_ID","THEATRE","THEATRE_ID" ) VALUES (4,112,'Luxe',223);
INSERT INTO THEATRE_MOVIE_MODEL ("ID","MOVIE_ID","THEATRE","THEATRE_ID" ) VALUES (5,113,'Udhayam',224);
INSERT INTO THEATRE_MOVIE_MODEL ("ID","MOVIE_ID","THEATRE","THEATRE_ID" ) VALUES (6,112,'Thangam',225);